apiVersion: v1
kind: Service
metadata:
  name: kafka-zookeeper-service
  labels:
    app: kafka-zookeeper
spec:
  type: NodePort
  selector:
    app: kafka-zookeeper
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
      nodePort: 30092