apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight-deployment
  namespace: product-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisinsight-deployment
  template:
    metadata:
      labels:
        app: redisinsight-deployment
    spec:
      automountServiceAccountToken: false
      containers:
        - name: redisinsight
          image: redis/redisinsight:2.70
          ports:
            - containerPort: 8001
          env:
            - name: RI_HOST
              value: "redis-service"
            - name: RI_PORT
              value: "6379"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: "512Mi"
            limits:
              memory: "512Mi"
              ephemeral-storage: "1Gi"
          volumeMounts:
            - name: redisinsight-storage
              mountPath: /db
      volumes:
        - name: redisinsight-storage
          persistentVolumeClaim:
            claimName: redisinsight-pvc