apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-statefulset
  namespace: product-app
spec:
  serviceName: redis-service
  replicas: 1
  selector:
    matchLabels:
      app: redis-statefulset
  template:
    metadata:
      labels:
        app: redis-statefulset
    spec:
      automountServiceAccountToken: false
      containers:
        - name: redis-stack
          image: redis/redis-stack:7.2.0-v19
          ports:
            - containerPort: 6379
            - containerPort: 8001
          volumeMounts:
            - name: redis-data
              mountPath: /data
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "256Mi"
            limits:
              memory: "256Mi"
              ephemeral-storage: "512Mi"
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "standard"
      resources:
        requests:
          storage: 5Gi