apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: product-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-deployment
  template:
    metadata:
      labels:
        app: redis-deployment
    spec:
      automountServiceAccountToken: false
      containers:
        - name: redis-stack
          image: redis/redis-stack:7.2.0-v19
          ports:
            - containerPort: 6379
            - containerPort: 8001
          volumeMounts:
            - name: redis-data
              mountPath: /data
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "256Mi"
            limits:
              memory: "256Mi"
              ephemeral-storage: "512Mi"
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-stack-pvc