apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: product-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-deployment
  template:
    metadata:
      labels:
        app: redis-deployment
    spec:
      automountServiceAccountToken: false
      containers:
        - name: redis
          image: redis:alpine3.22
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "256Mi"
            limits:
              memory: "256Mi"
              ephemeral-storage: "512Mi"