apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-stack-pvc
  namespace: product-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard