apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: product-app
  labels:
    app: redis-service
spec:
  selector:
    app: redis-deployment
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: NodePort