apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: product-app
spec:
  selector:
    app: postgres-database
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30007