apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-statefulset
  namespace: product-app
  labels:
    app: postgres-database
spec:
  serviceName: database-service
  replicas: 1
  selector:
    matchLabels:
      app: postgres-database
  template:
    metadata:
      labels:
        app: postgres-database
    spec:
      automountServiceAccountToken: false
      containers:
          - name: postgres-db
            image: postgres:15-alpine3.21
            ports:
              - containerPort: 5432
            resources:
              requests:
                cpu: "250m"
                memory: "256Mi"
                ephemeral-storage: "500Mi"
              limits:
                memory: "512Mi"
                ephemeral-storage: "1Gi"
            env:
              - name: POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: db-credentials
                    key: username
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: db-credentials
                    key: password
              - name: POSTGRES_DB
                value: productdb
              - name: PGDATA
                value: /var/lib/postgresql/data/pgdata
            volumeMounts:
              - name: postgres-storage
                mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "standard"
      resources:
        requests:
          storage: 10Gi